A better way to instrument the go compiler
Signed-off-by: Tim Henderson <tim.tadh@gmail.com>

diff --git a/bin/instrument-compile b/bin/instrument-compile
--- a/bin/instrument-compile
+++ b/bin/instrument-compile
@@ -4,14 +4,67 @@ if ! go install github.com/timtadh/dynagrok; then
 	echo "failed to compile dynagrok"
 	exit 1
 fi
-VERSION=release-1.8rc2
-TARGET=/tmp/$VERSION
-export GOROOT=$HOME/srcs/go-research
+
+dgpath=$1
+if [[ -z "$dgpath" ]]; then
+	echo "must supply the path to dynagrok's source tree as the first arg"
+	exit 1
+fi
+
+goroot=$2
+if [[ -z "$goroot" ]]; then
+	echo "must supply a GOROOT (which is a git checkout) as the second arg"
+	exit 1
+fi
+
+VERSION=$3
+if [[ -z "$VERSION" ]]; then
+	echo "must supply a go version as third arg"
+	exit 1
+fi
+
+HEAD=$(git -C $goroot rev-parse HEAD)
+COMMIT=$(git -C $goroot show-ref $VERSION)
+if [[ $? -eq 0 ]]; then
+	COMMIT=$(echo $COMMIT | cut -d \  -f 1)
+else
+	echo   $? $COMMIT
+	COMMIT=$VERSION
+fi
+
+echo "head   $HEAD"
+echo "commit $COMMIT"
+
+if [[ $HEAD != $COMMIT ]]; then
+	if ! git -C $goroot checkout $VERSION; then
+		echo "the version supplied could not be checked out"
+		exit 1
+	fi
+
+	if ! git -C $goroot clean -f; then
+		echo "could not a do clean"
+		exit 1
+	fi
+
+	( #subshell for compiling the go version
+		cd $goroot/src
+		if [ ! -f make.bash ]; then
+			echo "not a real goroot $goroot/src/make.bash does not exist"
+			exit 1
+		fi
+		OLDPATH=$PATH
+		source ./make.bash --no-banner
+	)
+fi
+
+TARGET=/tmp/go-$VERSION
+export GOROOT=$goroot
 export GOPATH=/tmp/fake-go-path
 rm -rf $TARGET
-dynagrok -d $HOME/stuff/research/dynagrok \
+dynagrok -d $dgpath \
 	instrument \
 		--keep-work -w $TARGET \
 		-o $TARGET/goroot/pkg/tool/linux_amd64/compile \
 		cmd/compile
 
+git -C $goroot checkout $HEAD
